### PR TITLE
Fix php notice for array

### LINKED ISSUE #48: Rate limit notice error
When you start to hit the API limit you get PHP notices. 

This is because the array is all lower case

### PR DESCRIPTION
**Pull request by paulsheldrake**
Also make sleep time dependent on the API specifics not hard-coded to a value.

Fixes #48

### CODE REVIEW

File: src/Rest.php [hunk 1]
```diff
@@ -69,10 +69,13 @@ private function execute($method, $action, $request = null)
...
             $headers     = $this->parseHeaders(substr($data, 0, $header_size));
-            if ($status === 400 &&
-                                (int) $headers['X-RateLimit-Remaining'] === 0) {
+            if (
+              $status === 400 &&
+              (int) $headers['x-ratelimit-remaining'] === 0) {
                 $i ++;
-                sleep(10);
+                $reset = $headers['x-ratelimit-reset'];
+                echo "Rate limit hit. Sleeping for: " . $reset . PHP_EOL;
```
Comment (simonschaufi) [inline src/Rest.php:77]: why an echo? I dislike echoing anything out here.

File: src/Rest.php [hunk 2]
```diff
@@ -69,10 +69,13 @@ private function execute($method, $action, $request = null)
             $status      = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
             $header_size = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
             $headers     = $this->parseHeaders(substr($data, 0, $header_size));
-            if ($status === 400 &&
-                                (int) $headers['X-RateLimit-Remaining'] === 0) {
+            if (
+              $status === 400 &&
+              (int) $headers['x-ratelimit-remaining'] === 0) {
```
Comment (simonschaufi) [inline src/Rest.php:74]: it's more readable if the brakets would be both in a new line

**Review by simonschaufi — CHANGES_REQUESTED** [review]

File: src/Rest.php (hunk 2 above)
Comment (paulsheldrake) [reply src/Rest.php]: updated

**Review by simonschaufi — APPROVED** [review]
